Makeover for CI/CD workflows, pre-commit & MkDocs
emmo-repo/EMMOntoPy pull request #485
Opened 2022-10-06 13:34 UTC by CasperWA

# Description:

Fixes #481 
Fixes #482 

### CI/CD

This PR implements a complete makeover for the CI/CD workflows, utilizing the [SINTEF/ci-cd](https://github.com/SINTEF/ci-cd) callable GitHub Actions workflows as well as the pre-commit hooks there.

Benefits of this makeover:

- Automatic updates of the underlying workflows.
- Remove `invoke` dependency and `tasks.py` file, since these `invoke` tasks are replaced by the hooks and workflows from SINTEF/ci-cd.
- Simplified workflow file contents, where only a few jobs are now explicit. Those, which are very EMMOntoPy-specific.

Possible drawbacks:

- "Outsourcing" workflows and formerly internal `invoke` tasks for pre-commit hooks can lead to less flexibility if changes are needed and not implemented in the external workflows/hooks.
- Decreased transparency. One now has to inspect the external workflows/hooks to understand _exactly_ what is going on.

Overall, I think this is a huge improvement and should ease CI/CD immensely.

### Documentation

Some updates in the MkDocs configuration were necessary to fix some presentation issues of certain documentation pages.
The table of contents (ToC) has been improved to exclude the `emmodoc` markdown template files under the "Examples" section.

## Type of change:

- [x] Bug fix.
- [ ] New feature.
- [x] Documentation update.

## Checklist:

This checklist can be used as a help for the reviewer.

- [ ] Is the code easy to read and understand?
- [ ] Are comments for humans to read, not computers to disregard?
- [ ] Does a new feature has an accompanying new test (in the CI or unit testing schemes)?
- [ ] Has the documentation been updated as necessary?
- [ ] Does this close the issue?
- [ ] Is the change limited to the issue?
- [ ] Are errors handled for all outcomes?
- [ ] Does the new feature provide new restrictions on dependencies, and if so is this documented?

## Comments:

2022-10-06 13:58 UTC, CasperWA commented
This is a draft until #486 has been resolved.

2022-10-07 06:32 UTC, francescalb commented on docs/index.md
> +- [EMMC-CSA](https://emmc.eu/);
Same as above

2022-10-07 06:51 UTC, CasperWA commented on README.md
> +- [EMMC-CSA](https://emmc.eu/);
Sure. But... 
![image](https://user-images.githubusercontent.com/43357585/194485664-9c2a41bf-61a6-45ee-9ca0-b4c91ce4efce.png)

2022-10-07 06:52 UTC, CasperWA commented on README.md
> +- [EMMC-CSA](https://emmc.eu/);
I think they've closed emmc.info down in favor of emmc.eu. Then I'd rather link to the new one - perhaps an "about EMMC" to be completely specific?

2022-10-07 06:52 UTC, CasperWA commented on docs/index.md
> +- [EMMC-CSA](https://emmc.eu/);
See conversation/comment thread above.

2022-10-10 09:47 UTC, francescalb requested changes
I think you suggestion of removing official support of python 3.6 is good. We have not been testing for that version until now. Alternatively, we have to rename the excel-file to .xls. I think that should work, but it is getting quite outdated.

2022-10-10 11:36 UTC, CasperWA commented
I have removed Python 3.6 support, while extending official support to include Python 3.8, 3.9, and 3.10 (by adding these versions specifically to the metadata in `setup.py` - and also running the test suite with these versions.

2022-10-10 11:39 UTC, CasperWA commented
@jesper-friis I'd like some input /review from you on this PR as well, especially regarding the supported Python version changes this will introduce (see #486 for reference).

2022-10-10 14:35 UTC, francescalb approved these changes
This looks good. I am however, a little hesitant about it being much less transparent now. I suggest we open an issue about documenting a bit more.

2022-10-10 14:37 UTC, CasperWA commented
Information on the finalization of this PR:
1. 2 approvals required
2. Branch protection rules update for `master` (and `ci/dependabot-updates`) to "require" the new/updated) workflows
3. Merge
4. Update other existing PRs with the newly merged updates to `master`

2022-10-10 14:39 UTC, CasperWA commented
> This looks good. I am however, a little hesitant about it being much less transparent now. I suggest we open an issue about documenting a bit more.

That's completely fair.
I have foreseen this (slightly) and applied myself to try and write some nice documentation for the workflows and pre-commit hooks I'm using here, which are coming from the [SINTEF/ci-cd](https://github.com/SINTEF/ci-cd) GitHub repository.
The documentation can be found [here](https://SINTEF.github.io/ci-cd).

But we should definitely extend the EMMOntoPy documentation for developers to include references to this other documentation.

2022-10-10 20:22 UTC, jesper-friis commented
> @jesper-friis I'd like some input /review from you on this PR as well, especially regarding the supported Python version changes this will introduce (see #486 for reference).

I agree with this suggestion.

2022-10-10 20:43 UTC, jesper-friis commented
> > This looks good. I am however, a little hesitant about it being much less transparent now. I suggest we open an issue about documenting a bit more.
> 
> That's completely fair. I have foreseen this (slightly) and applied myself to try and write some nice documentation for the workflows and pre-commit hooks I'm using here, which are coming from the [SINTEF/ci-cd](https://github.com/SINTEF/ci-cd) GitHub repository. The documentation can be found [here](https://SINTEF.github.io/ci-cd).
> 
> But we should definitely extend the EMMOntoPy documentation for developers to include references to this other documentation.

If we could improve the documentation of [SINTEF/ci-cd](https://github.com/SINTEF/ci-cd), I think delegating to those tools is only beneficially. See e.g. [cache](https://github.com/marketplace/actions/cache#usage) for a typical example of documentation a github action.

2022-10-11 09:15 UTC, CasperWA commented
> > > This looks good. I am however, a little hesitant about it being much less transparent now. I suggest we open an issue about documenting a bit more.
> > 
> > 
> > That's completely fair. I have foreseen this (slightly) and applied myself to try and write some nice documentation for the workflows and pre-commit hooks I'm using here, which are coming from the [SINTEF/ci-cd](https://github.com/SINTEF/ci-cd) GitHub repository. The documentation can be found [here](https://SINTEF.github.io/ci-cd).
> > But we should definitely extend the EMMOntoPy documentation for developers to include references to this other documentation.
> 
> If we could improve the documentation of [SINTEF/ci-cd](https://github.com/SINTEF/ci-cd), I think delegating to those tools is only beneficially and makes the ci/cd much easier to read. See e.g. [cache](https://github.com/marketplace/actions/cache#usage) for a typical example of documentation a github action.

It's important to understand that the SINTEF/ci-cd repository does _not_ provide actions, but rather _callable workflows_. I.e., complete workflows with it's own step-logic and actions usage.
Furthermore, it provides pre-commit hooks to autoupdate API reference documentation and the landing page when using the MkDocs framework.

I think the documentation is quite extensive as is, but everything can always be improved. Please visit the documentation [here](https://SINTEF.github.io/ci-cd) and evaluate for yourself.

2022-10-11 09:23 UTC, francescalb commented
> 

I think this looks quite OK already. Only thing is to add the documentation (link to this repo) for ontopy developers as you mention.

2022-10-11 09:34 UTC, merged