Removed LegacyVersion from ontopy.utils
emmo-repo/EMMOntoPy pull request #515
Opened 2022-12-12 17:58 UTC by francescalb

# Description:

## Type of change:

- [ ] Bug fix.
- [ ] New feature.
- [ ] Documentation update.

## Checklist:

This checklist can be used as a help for the reviewer.

- [ ] Is the code easy to read and understand?
- [ ] Are comments for humans to read, not computers to disregard?
- [ ] Does a new feature has an accompanying new test (in the CI or unit testing schemes)?
- [ ] Has the documentation been updated as necessary?
- [ ] Does this close the issue?
- [ ] Is the change limited to the issue?
- [ ] Are errors handled for all outcomes?
- [ ] Does the new feature provide new restrictions on dependencies, and if so is this documented?

## Comments:

2022-12-12 18:04 UTC, francescalb commented
LegacyVersion was removed from the package 'packaging'. It was noly used for type_checking, so removing should not be a problem.

2022-12-13 08:16 UTC, CasperWA reviewed
I don't think there is a need to remove `LegacyVersion` here?
Or does it not exist any more in the newest version of `packaging`?

2022-12-13 08:19 UTC, CasperWA commented
> I don't think there is a need to remove `LegacyVersion` here? Or does it not exist any more in the newest version of `packaging`?

Ah. I should just read your comment. Didn't find a reason for the PR at first because it wasn't in the PR description but buried underneath, sorry.

2022-12-13 08:22 UTC, CasperWA requested changes

2022-12-13 08:22 UTC, CasperWA commented on ontopy/utils.py
> +            "min_version should be either a str (Version). "
```suggestion
            "min_version should be either a str or packaging.Version. "
```

2022-12-13 08:22 UTC, CasperWA commented on ontopy/utils.py
> +    elif isinstance(min_version, (Version)):
```suggestion
    elif isinstance(min_version, Version):
```
This is not going to work if `Version` is only imported in the `TYPE_CHECKING` block!

2022-12-13 08:22 UTC, CasperWA commented on ontopy/utils.py
> +    from packaging.version import Version
Move this up and out of the `TYPE_CHECKING` block as `Version` is used explicitly in line 454 and not just as a type hint.

2022-12-13 08:22 UTC, CasperWA commented on ontopy/utils.py
> +    from packaging.version import parse as parse_version, Version
```suggestion
    from packaging.version import parse as parse_version
```

2022-12-13 08:22 UTC, CasperWA commented on ontopy/utils.py
> +    from packaging.version import parse as parse_version, Version
Import `Version` and the top of the file instead.

2022-12-13 12:10 UTC, CasperWA approved these changes

2022-12-13 12:11 UTC, merged