Flb/fix to pylint2.15.4
emmo-repo/EMMOntoPy pull request #535
Opened 2023-02-02 16:30 UTC by francescalb

# Description:
Pylint 2.15.4 introduced some new tests that were not followed. 
The code has been updated accordingly.

## Type of change:

- [x] Bug fix.
- [ ] New feature.
- [ ] Documentation update.

## Checklist:

This checklist can be used as a help for the reviewer.

- [ ] Is the code easy to read and understand?
- [ ] Are comments for humans to read, not computers to disregard?
- [ ] Does a new feature has an accompanying new test (in the CI or unit testing schemes)?
- [ ] Has the documentation been updated as necessary?
- [ ] Does this close the issue?
- [ ] Is the change limited to the issue?
- [ ] Are errors handled for all outcomes?
- [ ] Does the new feature provide new restrictions on dependencies, and if so is this documented?

## Comments:

2023-02-02 21:12 UTC, jesper-friis commented on ontopy/ontodoc.py
> +                # print(item.individual.is_instance_of)
This could be removed

2023-02-02 21:12 UTC, jesper-friis commented on ontopy/ontodoc.py
> +                print("a", points)
Remove

2023-02-02 21:13 UTC, jesper-friis commented on ontopy/ontodoc.py
> +                print("b", points)
More debugging to remove

2023-02-02 21:14 UTC, jesper-friis requested changes
Looks good. You should only remove some leftover debugging statements

2023-02-03 09:24 UTC, CasperWA approved these changes

2023-02-03 09:25 UTC, CasperWA reviewed
Did you want to update the pylint requirements as well, by the way?

2023-02-04 19:35 UTC, jesper-friis approved these changes

2023-02-04 19:42 UTC, merged