Added two additional exceptions to emmocheck
emmo-repo/EMMOntoPy pull request #577
Opened 2023-04-09 22:23 UTC by jesper-friis

# Description:
Added the following two exceptions to emmocheck
- foaf.logo comes from foaf and does not have a prefLabel
- Accept 3DPrinting in the DOAM ontology as a valid prefLabel, even though it does not start with a letter

## Type of change:

- [ ] Bug fix.
- [ ] New feature.
- [ ] Documentation update.

## Checklist:

This checklist can be used as a help for the reviewer.

- [ ] Is the code easy to read and understand?
- [ ] Are comments for humans to read, not computers to disregard?
- [ ] Does a new feature has an accompanying new test (in the CI or unit testing schemes)?
- [ ] Has the documentation been updated as necessary?
- [ ] Does this close the issue?
- [ ] Is the change limited to the issue?
- [ ] Are errors handled for all outcomes?
- [ ] Does the new feature provide new restrictions on dependencies, and if so is this documented?

## Comments:

2023-04-11 18:52 UTC, francescalb requested changes
I do not think the correct way to go about exceptions to emmocheck for ontologies except emmo itself is to add disregarded labels in emmocheck at top level. Then one should be able to add a list of labels to disregard in emmocheck.

2023-04-15 23:04 UTC, jesper-friis commented
> I do not think the correct way to go about exceptions to emmocheck for ontologies except emmo itself is to add disregarded labels in emmocheck at top level. Then one should be able to add a list of labels to disregard in emmocheck.

I fully agree. But these concepts are in EMMO.

2023-04-15 23:07 UTC, jesper-friis commented
Correction. 3DPrinting is not in EMMO any more - so I have removed the exception for that.

2023-04-24 06:22 UTC, francescalb approved these changes

2023-04-24 06:27 UTC, merged