Changed `is_defined` into a ThingClass property and improved its documentation.
emmo-repo/EMMOntoPy pull request #597
Opened 2023-04-30 10:39 UTC by jesper-friis

Also added tests.

Closes #563 

# Description:

## Type of change:

- [ ] Bug fix.
- [ ] New feature.
- [x] Documentation update.
- [x] Test update. 

## Checklist:

This checklist can be used as a help for the reviewer.

- [ ] Is the code easy to read and understand?
- [ ] Are comments for humans to read, not computers to disregard?
- [ ] Does a new feature has an accompanying new test (in the CI or unit testing schemes)?
- [ ] Has the documentation been updated as necessary?
- [ ] Does this close the issue?
- [ ] Is the change limited to the issue?
- [ ] Are errors handled for all outcomes?
- [ ] Does the new feature provide new restrictions on dependencies, and if so is this documented?

## Comments:

2023-05-09 11:22 UTC, francescalb requested changes

2023-05-09 15:42 UTC, jesper-friis commented on tests/test_ontopy.py
> +"""
I don't think implementing the test as a script defeat pytest in any way. It is picked up and runs nicely with pytest.

2023-05-09 15:55 UTC, jesper-friis commented on tests/test_ontopy.py
I updated the title and renamed the test to ontopy_tests/test_patch.py

2023-05-10 05:26 UTC, francescalb approved these changes

2023-05-10 05:44 UTC, merged