Skip checking dimensional units for domain ontologies that doesn't load this class.
emmo-repo/EMMOntoPy pull request #677
Opened 2023-11-21 14:26 UTC by jesper-friis

# Description
Do not check SI dimensional units if the checked domain ontology does not load that class.

## Type of change

- [x] Bug fix.
- [ ] New feature.
- [ ] Documentation update.
- [ ] Test update.

## Checklist

This checklist can be used as a help for the reviewer.

- [ ] Is the code easy to read and understand?
- [ ] Are comments for humans to read, not computers to disregard?
- [ ] Does a new feature has an accompanying new test (in the CI or unit testing schemes)?
- [ ] Has the documentation been updated as necessary?
- [ ] Does this close the issue?
- [ ] Is the change limited to the issue?
- [ ] Are errors handled for all outcomes?
- [ ] Does the new feature provide new restrictions on dependencies, and if so is this documented?

## Comments

2023-11-22 11:09 UTC, francescalb requested changes
In PR#658 test_emmocheck_module was added, but it is not actually testing anything when run with pytest. So apart tests/tools/test_emmocheck there i nothing that tests emmocheck here. The tool only checks that it runs, but nothing more (it passes as test even if the emmocheck fails) 

Please update the test so that it is actually run and then that it fails when emmocheck fails.

2023-11-22 12:19 UTC, jesper-friis commented
> Please update the test so that it is actually run and then that it fails when emmocheck fails.

This PR just skip testing dimensionalities for ontologies that doesn't import the relevant modules. Isn't adding general tests for emmocheck another issue?

2023-11-23 13:51 UTC, francescalb approved these changes

2023-11-23 13:51 UTC, francescalb approved these changes
Appoved, but make an issue about creating a test.

2023-11-23 16:56 UTC, merged